### ISSUE TITLE
Issue in scroll option at class="w-full flex-1 flex flex-col p-5 gap-3 max-h-[90vh] overflow-auto"

### ISSUE THREAD

**Issue by vikas148** [himanshurajora/lfc#3]
Issue in scroll option at class="w-full flex-1 flex flex-col p-5 gap-3 max-h-[90vh] overflow-auto"

https://github.com/himanshurajora/lfc/assets/71213518/8ed35641-f2a2-463e-b587-c6e47a68795e

**Comment by himanshurajora** [comment]
It's because we're loading the next page, but there is nothing to show. So the loader appears and then disappears again. Changing the loader animation might be a bit pleasant.

**Comment by himanshurajora** [comment]
Fixed after #4
